### PR TITLE
Update vulnerable gems

### PR DESCRIPTION
**Pull request by cmoel**

### CODE REVIEW

**Comment by descentintomael** [comment]
@cmoel why'd you delete this?  I'd actually like to accept that change.

**Comment by cmoel** [comment]
I'm sorry about that! Reopened.

**Comment by descentintomael** [comment]
Thanks. Do you need me to do a version bump?

**Comment by cmoel** [comment]
Thank for offering! We don't need a version bump because we're working off of a SHA. That said, it might be useful for others using this gem

**Pull request merged**
